# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1055, 728)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(3, 10, 591, 661))
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SpisokZametok = QtWidgets.QListWidget(self.centralwidget)
        self.SpisokZametok.setGeometry(QtCore.QRect(610, 40, 441, 131))
        self.SpisokZametok.setObjectName("SpisokZametok")
        self.AddZametka = QtWidgets.QPushButton(self.centralwidget)
        self.AddZametka.setGeometry(QtCore.QRect(610, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddZametka.setFont(font)
        self.AddZametka.setObjectName("AddZametka")
        self.DelZametka = QtWidgets.QPushButton(self.centralwidget)
        self.DelZametka.setGeometry(QtCore.QRect(840, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DelZametka.setFont(font)
        self.DelZametka.setObjectName("DelZametka")
        self.SaveZametka = QtWidgets.QPushButton(self.centralwidget)
        self.SaveZametka.setGeometry(QtCore.QRect(610, 240, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SaveZametka.setFont(font)
        self.SaveZametka.setObjectName("SaveZametka")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 310, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.SpisokZametok_2 = QtWidgets.QListWidget(self.centralwidget)
        self.SpisokZametok_2.setGeometry(QtCore.QRect(610, 340, 441, 131))
        self.SpisokZametok_2.setObjectName("SpisokZametok_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(610, 480, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.AddZametka_2 = QtWidgets.QPushButton(self.centralwidget)
        self.AddZametka_2.setGeometry(QtCore.QRect(610, 520, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddZametka_2.setFont(font)
        self.AddZametka_2.setObjectName("AddZametka_2")
        self.DelZametka_2 = QtWidgets.QPushButton(self.centralwidget)
        self.DelZametka_2.setGeometry(QtCore.QRect(840, 520, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DelZametka_2.setFont(font)
        self.DelZametka_2.setObjectName("DelZametka_2")
        self.SearchZametka = QtWidgets.QPushButton(self.centralwidget)
        self.SearchZametka.setGeometry(QtCore.QRect(610, 572, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SearchZametka.setFont(font)
        self.SearchZametka.setObjectName("SearchZametka")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Умные заметки"))
        self.textEdit.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("mainWindow", "Список заметок"))
        self.AddZametka.setText(_translate("mainWindow", "Создать заметку"))
        self.DelZametka.setText(_translate("mainWindow", "Удалить заметку"))
        self.SaveZametka.setText(_translate("mainWindow", "Сохранить заметку"))
        self.label_2.setText(_translate("mainWindow", "Список тегов"))
        self.lineEdit.setPlaceholderText(_translate("mainWindow", "Введите тег..."))
        self.AddZametka_2.setText(_translate("mainWindow", "Добавить к заметке"))
        self.DelZametka_2.setText(_translate("mainWindow", "Открепить от заметки"))
        self.SearchZametka.setText(_translate("mainWindow", "🔎Искать заметки по тегу🔎"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
